version: '3.1'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:10-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
